### ISSUE TITLE
Unable to install packages

### ISSUE THREAD

**Issue by ertanhasani** [sign-language-processing/transcription#11]
Hi,

I am having problems running `pip install -e '.[dev]'`, i get the following error:
```
ERROR: Could not find a version that satisfies the requirement mediapipe; extra == "dev" (from sign-transcription[dev]) (from versions: none)
ERROR: No matching distribution found for mediapipe; extra == "dev"
```

I also tried to install it manually by running `pip install mediapipe`, but i get:
```
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

I also have the same issue when trying to install `pip install diffusion`:
```
ERROR: Cannot install diffusion==6.7.0, diffusion==6.7.10, diffusion==6.7.2, diffusion==6.7.3, diffusion==6.7.5, diffusion==6.8.0, diffusion==6.8.1, diffusion==6.8.2, diffusion==6.8.3, diffusion==6.8.4, diffusion==6.8.5, diffusion==6.8.6, diffusion==6.8.7, diffusion==6.8.8, diffusion==6.9.0 and diffusion==6.9.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    diffusion 6.9.1 depends on diffusion-core==0.0.28
    diffusion 6.9.0 depends on diffusion-core==0.0.28
    diffusion 6.8.8 depends on diffusion-core==0.0.16
    diffusion 6.8.7 depends on diffusion-core==0.0.16
    diffusion 6.8.6 depends on diffusion-core==0.0.16
    diffusion 6.8.5 depends on diffusion-core==0.0.16
    diffusion 6.8.4 depends on diffusion-core==0.0.16
    diffusion 6.8.3 depends on diffusion-core==0.0.16
    diffusion 6.8.2 depends on diffusion-core==0.0.16
    diffusion 6.8.1 depends on diffusion-core==0.0.16
    diffusion 6.8.0 depends on diffusion-core==0.0.16
    diffusion 6.7.10 depends on diffusion-cbor==6.7.10
    diffusion 6.7.5 depends on diffusion-cbor==6.7.5
    diffusion 6.7.3 depends on diffusion-cbor==6.7.3
    diffusion 6.7.2 depends on diffusion-cbor==6.7.2
    diffusion 6.7.0 depends on diffusion-cbor==6.7.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

I am following though all steps described in the readme, and i tried it with both python 3.10 and 3.9. 

In the other side it seems like i cant find that `diffusion.one_shot` anywhere in the diffusion library as well as i am not able to run all commands, i can only do it for `pose_to_video` and the others are `command not found`.

Do i need to install specific versions of the python or packages in order make it work? Or maybe there is some third party library that i am missing?

Thank you!

p.s. you've done some really good work! ⭐️

**Comment by AmitMY** [comment]
I am concerned that `pip install mediapipe` does not work for you.

What operating system are you using? are you using conda?
1. Are you on an apple device? if so, which? (m1/intel)
2. Are you using docker by any chance?

**Comment by ertanhasani** [comment]
> I am concerned that `pip install mediapipe` does not work for you.
> 
> What operating system are you using? are you using conda?
> 
> 1. Are you on an apple device? if so, which? (m1/intel)
> 2. Are you using docker by any chance?

I am using M1 Apple chip and i have installed anaconda. 
I have docker installed on my machine but Im not using it for this project.

**Comment by AmitMY** [comment]
Mediapipe and others don't have distributions for `arm` chips. You have to install the `amd64` versions of the packages, which is easier to do inside a docker machine

**Comment by AssafBok** [comment]
> > I am concerned that `pip install mediapipe` does not work for you.
> > What operating system are you using? are you using conda?
> > 
> > 1. Are you on an apple device? if so, which? (m1/intel)
> > 2. Are you using docker by any chance?
> 
> I am using M1 Apple chip and i have installed anaconda. I have docker installed on my machine but Im not using it for this project.

@ertanhasani 
I am using the same chip and managed to install it, it seems to work.
For your issue, try this:
1. install anaconda3 with the installer they are providing for M1. It will be better than using brew, for that matter.
2. use bash (by typing `bash` in the terminal) and do these: ( bash is working on my machine, but zsh is not - for now)
2.a run `conda init bash` / `conda init zsh` => start new terminal session 
2.b Paste the code below with your local conda3 path (`which conda` command should return the path if not, try this path `/Users/YOUR_USERNAME/anaconda3`) in the relevant places in these file/s: `.bashrc` / `.zshrc`, and save cahnges.
For bash:
`__conda_setup="$('/path/to/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/path/to/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/path/to/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/path/to/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup`
for zsh:
`__conda_setup="$('/path/to/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/path/to/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/path/to/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/path/to/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup`
2.c you can use this `source ~/.bashrc` / `source ~/.zshrc` to apply the changes to the current session or start a new session.
3. run this `conda activate sign` => see the `(sign)` in the command line prefix.
4. run `pip install ".[dev]"` for zsh (so that zsh doesn't try to interpret the square brackets) or `pip install .[dev]` for bash  within the main dir (the one that holds pyproject.toml file - verify with `ls -a`).
5.  run this `export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`
6. run the `pip install mediapipe` 
7. run `video_to_pose -i sign.mp4 --format mediapipe -o sign.pose` => expect this: 
<img width="606" alt="image" src="https://github.com/sign-language-processing/transcription/assets/116381145/e3e09460-f000-4ced-a4a6-9d7cf81b6075">

8. for pympi install pympi-ling `pip install pympi-ling`

BTW, 
Running this line by line: (from README)
`pip install mediapipe`
`video_to_pose -i sign.mp4 --format mediapipe -o sign.pose` didn't work for me, but pasting it together and running it worked 🤷. 

I hope this helps
